[project]
name = "parimitham"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2",
    "django-tasks>=0.7.0",
    "hypercorn>=0.17.3",
    "rich>=14.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.8",
]
